---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paper-rcon-web
spec:
  interval: 30m
  chart:
    spec:
      chart: rcon-web-admin
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
      interval: 30m
  values:
    fullnameOverride: paper-rcon-web
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: rcon.hades.casa
        lbipam.cilium.io/ips: 10.4.0.131
      externalTrafficPolicy: Local
    ingress:
      enabled: false
    rconWeb:
      isAdmin: true
      game: minecraft
      passwordExistingSecret: paper-rcon
      passwordKey: rcon-password
      rconHost: paper-rcon.default.svc.cluster.local
      rconPort: 25575
      rconPasswordExistingSecret: paper-rcon
      rconPasswordKey: rcon-password
    extraEnv:
      TZ: America/New_York
      RWA_WEBSOCKET_URL: ws://rcon.hades.casa:4327
      RWA_WEBSOCKET_URL_SSL: wss://rcon.hades.casa:4327
