---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paper-rcon-web
spec:
  interval: 30m
  chart:
    spec:
      chart: rcon-web-admin
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
      interval: 30m
  values:
    fullnameOverride: paper-rcon-web
    service:
      type: LoadBalancer
    ingress:
      enabled: true
    rconWeb:
      isAdmin: true
      game: minecraft
      passwordExistingSecret: paper-rcon
      passwordKey: rcon-password
      rconHost: paper-rcon.default.svc.cluster.local
      rconPort: 25575
      rconPasswordExistingSecret: paper-rcon
      rconPasswordKey: rcon-password
    extraEnv:
      TZ: America/New_York
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Service
              name: paper-rcon-web
            patch: |
              - op: add
                path: /metadata/annotations/lbipam.cilium.io~1ips
                value: 10.4.0.131
              - op: add
                path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
                value: rcon.hades.casa
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: paper-rcon-web
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: RWA_WEBSOCKET_URL
                  value: "ws://10.4.0.131:4327"
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: RWA_WEBSOCKET_URL_SSL
                  value: "wss://10.4.0.131:4327"
