---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paper
spec:
  interval: 1h
  chart:
    spec:
      chart: minecraft
      version: 4.26.0
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
      interval: 1h
  values:
    # Image configuration
    image: itzg/minecraft-server
    imageTag: 2025.10.5@sha256:0062e45ec8aa8bdbeeb6b4ad0e15df804c4525f0e208b66d899ab677230ee0e9

    # Pod annotations
    podAnnotations:
      reloader.stakater.com/auto: "true"

    # Security context
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      runAsNonRoot: true

    # Minecraft server configuration
    minecraftServer:
      eula: true
      version: "1.21.10"
      type: PAPER
      paperChannel: experimental
      difficulty: hard
      whitelist: ""  # Provided via secret
      ops: ""  # Provided via secret
      icon: https://i.imgur.com/1Pzv8xx.png
      overrideIcon: true
      maxWorldSize: 29999984
      allowNether: true
      announcePlayerAchievements: true
      enableCommandBlock: true
      forceGameMode: true
      generateStructures: true
      hardcore: false
      snooperEnabled: false
      maxPlayers: 20
      maxTickTime: 60000
      spawnAnimals: true
      spawnMonsters: true
      spawnNPCs: true
      spawnProtection: 0
      viewDistance: 32
      pvp: true
      levelSeed: "1691256543523180978"
      gameMode: survival
      motd: "Powered by 100% §kVOID §r energy.§r\\n                     (っ◕‿◕)っ"
      worldSaveName: Gaia

      # RCON
      rcon:
        enabled: true
        port: 25575
        password: ""  # Provided via secret
        serviceType: ClusterIP

      # Server properties
      serviceType: ClusterIP
      serviceAnnotations:
        external-dns.alpha.kubernetes.io/hostname: mc.hades.casa
        external-dns.alpha.kubernetes.io/target: mc-router.hades.casa
        mc-router.itzg.me/externalServerName: mc.hades.casa

    # Extra environment variables
    extraEnv:
      TZ: America/New_York
      USE_AIKAR_FLAGS: "true"
      USE_MEOWICE_FLAGS: "true"
      MAX_MEMORY: 8G
      BROADCAST_RCON_TO_OPS: "false"
      PAUSE_WHEN_EMPTY_SECONDS: "600"

    # Environment variables from secrets
    envFrom:
      - secretRef:
          name: paper-secret

    # Liveness and readiness probes
    livenessProbe:
      enabled: true
      command:
        - mc-health
      initialDelaySeconds: 30
      periodSeconds: 60

    readinessProbe:
      enabled: true
      command:
        - mc-health
      initialDelaySeconds: 30
      periodSeconds: 5

    startupProbe:
      enabled: true
      command:
        - mc-health
      failureThreshold: 300
      periodSeconds: 1

    # Resources
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 8Gi

    # Persistence
    persistence:
      dataDir:
        enabled: true
        existingClaim: paper
