---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app localai
spec:
  interval: 1h
  chart:
    spec:
      chart: local-ai
      version: 3.4.2
      sourceRef:
        kind: HelmRepository
        name: *app
      interval: 15m
  values:
    replicaCount: 1
    fullnameOverride: localai
    deployment:
      image:
        repository: quay.io/go-skynet/local-ai
        tag: v3.8.0-gpu-nvidia-cuda-12
      env:
        threads: 4
        F16: true
        API_KEY: "sk-local"
      modelsPath: /models
      modelsVolume:
        enabled: true
        pvc:
          enabled: true
          existingClaim: localai
    runtimeClassName: nvidia
    persistence:
      models:
        enabled: false
      output:
        enabled: false
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
        nvidia.com/gpu: 1
      limits:
        memory: 24Gi
        nvidia.com/gpu: 1
    service:
      type: ClusterIP
      ports:
        http:
          port: 8080
