---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: localai
spec:
  hostnames:
    - localai.hades.casa
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: localai
          port: 80
