---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chaptarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: chaptarr-secret
    template:
      data:
        CHAPTARR__AUTH__APIKEY: "{{ .CHAPTARR_API_KEY }}"
  dataFrom:
    - extract:
        key: chaptarr
