---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app librechat
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    global:
      librechat:
        existingSecretName: librechat-credentials-env
        existingSecretApiKey: OPENAI_API_KEY
    librechat:
      configEnv:
        CUSTOM_FOOTER: "Copyright Â© 2025 Nyx. All rights reserved."
        DEBUG_PLUGINS: "false"
        MEILI_NO_ANALYTICS: "true"
      existingSecretName: librechat-credentials-env
      configYamlContent: |
        version: 1.2.9
        cache: true
        speech:
          tts:
            elevenlabs:
              apiKey: '${ELEVENLABS_API_KEY}'
              model: 'eleven_v3'
              voices: ['H2cdv8R2nEdoRT9ji2xP', 'Ttn6dlQvgqQ9d7by8NNT', 'LmHPRoS1O5KyGE3oXRbb', 'I1X1J5pzMOURLxATlhpe']
          speechTab:
            conversationMode: true
            advancedMode: false
            speechToText:
              engineSTT: "browser"
              languageSTT: "English (US)"
              autoTranscribeAudio: true
              decibelValue: -45
              autoSendText: 0
            textToSpeech:
              engineTTS: "external"
              voice: "H2cdv8R2nEdoRT9ji2xP"
              languageTTS: "en"
              automaticPlayback: true
              playbackRate: 1.0
              cacheTTS: true
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 1Gi
    mongodb:
      image:
        registry: cgr.dev
        repository: chainguard/mongodb
